{
 "title": "FusionCache metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(fusioncache_cache_hit_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval])) / sum(irate(fusioncache_cache_get_or_set_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval]))",
     "legendFormat": "Cache hit ratio"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(fusioncache_cache_hit_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval])) / sum(irate(fusioncache_cache_get_or_set_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval]))",
     "legendFormat": "cache hit %"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{job=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{job=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_request_duration_seconds_bucket{job=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket{job=\"api\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5 percentile (average)"
    }
   ]
  },
  {
   "title": "Cache stats",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(fusioncache_cache_get_or_set_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval]))",
     "legendFormat": "get per second"
    },
    {
     "expr": "sum(irate(fusioncache_cache_hit_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval]))",
     "legendFormat": "hit per second"
    },
    {
     "expr": "sum(irate(fusioncache_cache_miss_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval]))",
     "legendFormat": "miss per second"
    },
    {
     "expr": "sum(irate(fusioncache_eager_refresh_total{fusioncache_cache_name=\"SampleCache\"}[$__rate_interval]))",
     "legendFormat": "eager refresh per second"
    }
   ]
  }
 ]
}